import * as functions from "firebase-functions/v1";
export declare const cleanupProfilePictures: functions.CloudFunction<functions.storage.ObjectMetadata>;
export declare const onActivityCreated: functions.CloudFunction<functions.firestore.QueryDocumentSnapshot>;
export declare const onActivityUpdated: functions.CloudFunction<functions.Change<functions.firestore.QueryDocumentSnapshot>>;
export declare const onActivityDeleted: functions.CloudFunction<functions.firestore.QueryDocumentSnapshot>;
export declare const onServiceCreated: functions.CloudFunction<functions.firestore.QueryDocumentSnapshot>;
export declare const onServiceUpdated: functions.CloudFunction<functions.Change<functions.firestore.QueryDocumentSnapshot>>;
export declare const onServiceDeleted: functions.CloudFunction<functions.firestore.QueryDocumentSnapshot>;
export declare const onUrgentFamilyFlagged: functions.CloudFunction<functions.Change<functions.firestore.QueryDocumentSnapshot>>;
export declare const onMissionaryAssignmentCreated: functions.CloudFunction<functions.firestore.QueryDocumentSnapshot>;
export declare const onCouncilAnnotationCreated: functions.CloudFunction<functions.firestore.QueryDocumentSnapshot>;
export declare const onCouncilAnnotationUpdated: functions.CloudFunction<functions.Change<functions.firestore.QueryDocumentSnapshot>>;
export declare const onCouncilAnnotationDeleted: functions.CloudFunction<functions.firestore.QueryDocumentSnapshot>;
export declare const onNewUserRegistered: functions.CloudFunction<functions.firestore.QueryDocumentSnapshot>;
export declare const dailyNotifications: functions.CloudFunction<unknown>;
export declare const weeklyNotifications: functions.CloudFunction<unknown>;
export declare const councilNotifications: functions.CloudFunction<unknown>;
export declare const syncOnMembersWrite: functions.CloudFunction<functions.Change<functions.firestore.DocumentSnapshot>>;
export declare const syncOnAnnotationsWrite: functions.CloudFunction<functions.Change<functions.firestore.DocumentSnapshot>>;
export declare const syncOnMinisteringWrite: functions.CloudFunction<functions.Change<functions.firestore.DocumentSnapshot>>;
export declare const syncOnMinisteringDistrictsWrite: functions.CloudFunction<functions.Change<functions.firestore.DocumentSnapshot>>;
export declare const syncOnMinisteringInterviewsWrite: functions.CloudFunction<functions.Change<functions.firestore.DocumentSnapshot>>;
export declare const syncOnActivitiesWrite: functions.CloudFunction<functions.Change<functions.firestore.DocumentSnapshot>>;
export declare const syncOnServicesWrite: functions.CloudFunction<functions.Change<functions.firestore.DocumentSnapshot>>;
export declare const syncOnMissionaryAssignmentsWrite: functions.CloudFunction<functions.Change<functions.firestore.DocumentSnapshot>>;
export declare const syncOnInvestigatorsWrite: functions.CloudFunction<functions.Change<functions.firestore.DocumentSnapshot>>;
export declare const syncOnNewConvertFriendsWrite: functions.CloudFunction<functions.Change<functions.firestore.DocumentSnapshot>>;
export declare const syncOnHealthConcernsWrite: functions.CloudFunction<functions.Change<functions.firestore.DocumentSnapshot>>;
export declare const syncOnBirthdaysWrite: functions.CloudFunction<functions.Change<functions.firestore.DocumentSnapshot>>;
export declare const syncOnBaptismsWrite: functions.CloudFunction<functions.Change<functions.firestore.DocumentSnapshot>>;
export declare const syncOnFsTrainingsWrite: functions.CloudFunction<functions.Change<functions.firestore.DocumentSnapshot>>;
export declare const syncOnFsAnnotationsWrite: functions.CloudFunction<functions.Change<functions.firestore.DocumentSnapshot>>;
export declare const syncOnConvertsWrite: functions.CloudFunction<functions.Change<functions.firestore.DocumentSnapshot>>;
export declare const syncOnFutureMembersWrite: functions.CloudFunction<functions.Change<functions.firestore.DocumentSnapshot>>;
export declare const syncOnUsersWrite: functions.CloudFunction<functions.Change<functions.firestore.DocumentSnapshot>>;
/** Callable: re-broadcast a sync signal (rare; header refresh is the client fallback). */
export declare const requestDataSyncSignal: functions.HttpsFunction & functions.Runnable<any>;
//# sourceMappingURL=index.d.ts.map