/* global importScripts, caches, fetch */

// Attach Firebase Messaging background handlers to the real root service worker
// generated by next-pwa so push delivery uses the same worker the client registers.
importScripts('/firebase-messaging-sw.js');

/**
 * Extra offline helpers for the custom worker bridge:
 * - Warm-cache URLs requested by the app (pages, icons, photos)
 * - Cache-first for Firebase Storage / GCS images
 * - SKIP_WAITING support for manual activation
 */

const IMAGE_CACHE = 'firebase-images-v1';
const WARM_CACHE = 'pages-warm-v1';

const IMAGE_HOST_RE =
  /firebasestorage\.googleapis\.com|storage\.googleapis\.com|\.firebasestorage\.app$/i;

self.addEventListener('message', (event) => {
  const data = event.data;
  if (!data || typeof data !== 'object') return;

  if (data.type === 'SKIP_WAITING') {
    self.skipWaiting();
    return;
  }

  if (data.type === 'WARM_CACHE_URLS' && Array.isArray(data.urls)) {
    event.waitUntil(warmCacheUrls(data.urls));
  }
});

async function warmCacheUrls(urls) {
  const pageCache = await caches.open(WARM_CACHE);
  const imageCache = await caches.open(IMAGE_CACHE);

  await Promise.all(
    urls.map(async (raw) => {
      if (typeof raw !== 'string' || !raw) return;
      try {
        const isImage =
          IMAGE_HOST_RE.test(raw) ||
          /\.(png|jpe?g|webp|gif|svg|ico)(\?|$)/i.test(raw);
        const target = isImage ? imageCache : pageCache;
        const existing = await target.match(raw);
        if (existing) return;

        const sameOrigin = raw.startsWith(self.location.origin) || raw.startsWith('/');
        const response = await fetch(raw, {
          credentials: sameOrigin ? 'same-origin' : 'omit',
          mode: 'cors',
          cache: 'reload',
        });
        if (response && (response.ok || response.type === 'opaque')) {
          await target.put(raw, response.clone());
        }
      } catch {
        // ignore individual warm failures
      }
    })
  );
}

// Image cache-first for Firebase/GCS (complements Workbox runtimeCaching)
self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  let url;
  try {
    url = new URL(request.url);
  } catch {
    return;
  }

  if (!IMAGE_HOST_RE.test(url.hostname)) return;

  event.respondWith(
    (async () => {
      const cache = await caches.open(IMAGE_CACHE);
      const cached = await cache.match(request);
      if (cached) return cached;

      try {
        const response = await fetch(request);
        if (response && response.ok) {
          event.waitUntil(cache.put(request, response.clone()));
        }
        return response;
      } catch {
        return (
          cached ||
          new Response('', { status: 503, statusText: 'Offline image unavailable' })
        );
      }
    })()
  );
});
